import Header from "@/components/header/header";
import { ModalStoreProvider } from "@/providers/modal-store-provider";
import ToastProvider from "@/providers/toast-provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "./_fonts/PretendardVariable.woff2",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={myFont.className}>
        <ToastProvider>
          <ModalStoreProvider>
            <Header />
            <div className="h-screen bg-background-primary">{children}</div>
          </ModalStoreProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
